[[questions]]
type="MultipleChoice"
prompt.prompt = "What is the difference between a module and a namespace in Cairo?"
answer.answer = "There is no difference between a module and a namespace in Cairo."
prompt.distractors = [
    "A module is a collection of related functions and types, while a namespace is a single function or type",
    "A module is a single function or type, while a namespace is a collection of related functions and types.",
    " A module is a part of a namespace."
]

[[questions]]
type="MultipleChoice"
prompt.prompt = "
Does this compile?:
```rust
//in src/menu/desert.cairo
#[derive(Drop, Debug)]
pub struct Icecream{flavour: felt252}

//in src/menu.cairo
pub mod desert;

//in src/lib.cairo
pub mod restaurant;
use restaurant::menu::Desert;

fn main() {
    let order = Icecream {flavour: 'vanilla'};
    println!("I'd like to order  {:?}!", order);
}
```
"
answer.answer = "Yes"
prompt.distractors = ["No"]
context = "fields in structs need to be declared as public so that they are visible."