[[questions]]
type="MultipleChoice"
prompt.prompt = "What is the difference between a module and a namespace in Cairo?"
answer.answer = "There is no difference between a module and a namespace in Cairo."
prompt.distractors = [
    "A module is a collection of related functions and types, while a namespace is a single function or type",
    "A module is a single function or type, while a namespace is a collection of related functions and types.",
    " A module is a part of a namespace."
]

[[questions]]
type="ShortAnswer"
prompt.prompt = "What can you add to line this to make it compile?
```rust
fn add_num(n1: u16, n2: u16) -> u16 {
    let result: u16 = n1 + n2;
    result
}

mod calculator {
    fn calculate_sum(num1: u16, num2: u16){
        add_num(num1, num2);
    }
    fn calculate(n1: u8) -> bool {
        if n1 > 20 {
            return true;
        }
        return false;
}
}
```
"
answer.answer = "super::"
context = "The function calculate_sum, which is defined in the calculator module, invokes the add_num function that is defined in the parent module. This is achieved by specifying the path to add_num using the super:: prefix."